export const GET_MODEL_SUCCESS= "GET_MODEL_SUCCESS";
export const GET_VEHICLES_SUCCESS="GET_VEHICLES_SUCCESS"

export const SELECT_VEHICLES="SELECT_VEHICLES"
export const REMOVE_TO_CART="REMOVE_TO_CART"


export const CREATE_PRODUCTS_SUCCESS="CREATE_PRODUCTS_SUCCESS"
export const UPDATE_PRODUCTS_SUCCESS="UPDATE_PRODUCTS_SUCCESS"
