export const GET_MODEL_SUCCESS= "GET_MODEL_SUCCESS";
export const GET_VEHICLES_SUCCESS="GET_VEHICLES_SUCCESS"

export const SELECT_VEHICLES="SELECT_VEHICLES"
export const SAVE_VEHICLE_SUCCESS="SAVE_VEHICLE_SUCCESS"



